(()=>{
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const form=$('#brief-form'), scoreValue=$('#score-value'), scoreRing=$('#score-ring'), readiness=$('#readiness'), readinessLabel=$('#readiness-label'), checks=$('#checks'), generateBtn=$('#generate-button'), results=$('#results'), outputsGrid=$('#outputs-grid'), sourceSummary=$('#source-summary'), toast=$('#toast');
const STORAGE='spln-briefcom-v2'; let generated=null, toastTimer;

const raw={service:'Services techniques',requester:'',source:'',validator:'',urgency:'important',subject:'Travaux rue de la Gare mardi',type:'travaux',audience:'',change:'Des travaux sont prévus rue de la Gare mardi.',impact:'',action:'',noAction:false,startDate:'',startTime:'',endDate:'',endTime:'',location:'Rue de la Gare',contact:'',channels:['site','social']};
const complete={service:'Services techniques',requester:'Responsable voirie',source:'Note des services techniques du 28 août 2026',validator:'Maire / Cabinet',urgency:'important',subject:'Travaux rue de la Gare mardi 1er septembre',type:'travaux',audience:'Riverains, automobilistes et usagers des transports',change:'Des travaux de réfection de la chaussée seront réalisés rue de la Gare.',impact:'La circulation sera alternée et le stationnement interdit sur la zone de chantier. L’accès aux riverains restera maintenu.',action:'Anticiper les déplacements et respecter la signalisation temporaire mise en place.',noAction:false,startDate:'2026-09-01',startTime:'08:00',endDate:'2026-09-01',endTime:'17:00',location:'Rue de la Gare, entre la rue de Larchant et l’avenue Carnot',contact:'Accueil de la mairie · mairie@spln.fr',channels:['site','social','notification','reception']};

const rules=[
 ['subject',9,true,'Préciser l’objet de la communication.','Objet clairement identifié.',d=>d.subject.trim().length>=8],
 ['service',7,true,'Identifier le service demandeur.','Service demandeur identifié.',d=>!!d.service],
 ['source',8,false,'Ajouter la source de référence.','Source de référence traçable.',d=>d.source.trim().length>=5],
 ['validator',7,false,'Définir qui doit valider.','Responsable de validation défini.',d=>!!d.validator],
 ['startDate',8,true,'Renseigner la date de début.','Date de début renseignée.',d=>!!d.startDate],
 ['location',7,true,'Préciser le lieu ou le périmètre.','Lieu ou périmètre précisé.',d=>d.location.trim().length>=4],
 ['audience',9,true,'Identifier le public concerné.','Public concerné identifié.',d=>d.audience.trim().length>=5],
 ['change',14,true,'Expliquer précisément ce qui se passe.','Fait principal suffisamment explicite.',d=>d.change.trim().length>=20],
 ['impact',9,true,'Préciser la conséquence pour l’habitant.','Conséquence concrète précisée.',d=>d.impact.trim().length>=10],
 ['action',9,true,'Indiquer l’action attendue ou cocher information uniquement.','Action attendue clarifiée.',d=>d.noAction||d.action.trim().length>=10],
 ['contact',7,true,'Ajouter un contact public.','Contact public renseigné.',d=>d.contact.trim().length>=5],
 ['channels',6,true,'Sélectionner au moins un canal.','Canaux de diffusion sélectionnés.',d=>d.channels.length>0]
];

function data(){const f=new FormData(form);return{service:f.get('service')||'',requester:f.get('requester')||'',source:f.get('source')||'',validator:f.get('validator')||'',urgency:f.get('urgency')||'normal',subject:f.get('subject')||'',type:f.get('type')||'travaux',audience:f.get('audience')||'',change:f.get('change')||'',impact:f.get('impact')||'',action:f.get('action')||'',noAction:$('#no-action').checked,startDate:f.get('startDate')||'',startTime:f.get('startTime')||'',endDate:f.get('endDate')||'',endTime:f.get('endTime')||'',location:f.get('location')||'',contact:f.get('contact')||'',channels:$$('input[name="channels"]:checked').map(x=>x.value)}}
function setData(d){const ids={service:'service',requester:'requester',source:'source',validator:'validator',urgency:'urgency',subject:'subject',type:'type',audience:'audience',change:'change',impact:'impact',action:'action',startDate:'start-date',startTime:'start-time',endDate:'end-date',endTime:'end-time',location:'location',contact:'contact'};Object.entries(ids).forEach(([k,id])=>{const e=$('#'+id);if(e)e.value=d[k]??''});$('#no-action').checked=!!d.noAction;$$('input[name="channels"]').forEach(x=>x.checked=(d.channels||[]).includes(x.value));syncAction();update();save()}
function evaluation(d){let score=0;const passed=[],missing=[];rules.forEach(r=>{(r[5](d)?passed:missing).push(r);if(r[5](d))score+=r[1]});const substantive=[d.subject,d.service,d.source,d.audience,d.change,d.impact,d.action,d.startDate,d.location,d.contact].some(v=>String(v||'').trim());if(!substantive)score=0;const warnings=[];if(d.startDate&&d.endDate&&d.endDate<d.startDate)warnings.push('La date de fin est antérieure à la date de début.');if(d.startDate&&!d.startTime)warnings.push('Une heure de début limiterait les demandes de précision.');if(d.endDate&&!d.endTime)warnings.push('L’heure de fin n’est pas renseignée.');if(d.urgency==='urgent'&&!d.channels.includes('notification'))warnings.push('Une information urgente devrait inclure une notification.');if(!d.requester.trim())warnings.push('Ajouter un référent interne facilite les corrections tardives.');const blockers=missing.filter(r=>r[2]);return{score,passed:substantive?passed:[],missing,warnings:substantive?warnings:[],canGenerate:score>=85&&!blockers.length&&!warnings.some(x=>x.includes('antérieure'))}}
function update(){const d=data(),e=evaluation(d);scoreValue.textContent=e.score;scoreRing.style.setProperty('--score',e.score);scoreRing.setAttribute('aria-label',`Score de clarté ${e.score} sur 100`);generateBtn.disabled=!e.canGenerate;readiness.dataset.state=e.canGenerate?'ready':'incomplete';readinessLabel.textContent=e.canGenerate?'Brief prêt à générer':e.score?'Brief incomplet':'Commencez le brief';const list=[];e.missing.slice(0,5).forEach(r=>list.push(`<div class="check missing"><i>!</i><span>${esc(r[3])}</span></div>`));e.warnings.slice(0,3).forEach(w=>list.push(`<div class="check warn"><i>?</i><span>${esc(w)}</span></div>`));if(e.canGenerate)list.push('<div class="check ok"><i>✓</i><span>Toutes les informations indispensables sont présentes.</span></div>');else if(!list.length)list.push('<div class="check warn"><i>?</i><span>Renseignez les premiers champs pour lancer le contrôle.</span></div>');checks.innerHTML=list.join('');save()}
function syncAction(){const box=$('#no-action'),field=$('#action');field.disabled=box.checked;if(box.checked)field.value='';}
function save(){try{localStorage.setItem(STORAGE,JSON.stringify(data()))}catch{}}
function restore(){try{const d=JSON.parse(localStorage.getItem(STORAGE));if(d&&typeof d==='object'){setData(d);return true}}catch{}return false}
function reset(){form.reset();$$('input[name="channels"]').forEach((x,i)=>x.checked=i<2);$('#no-action').checked=false;generated=null;results.hidden=true;try{localStorage.removeItem(STORAGE)}catch{}syncAction();update();show('Brief réinitialisé.')}

function generate(){const d=data(),e=evaluation(d);if(!e.canGenerate){show('Le brief doit être complété avant génération.');return}const outs=buildOutputs(d);generated={d,outs};sourceSummary.innerHTML=`<div><small>Service</small><b>${esc(d.service)}</b></div><div><small>Source faisant foi</small><b>${esc(d.source)}</b></div><div><small>Validation</small><b>${esc(d.validator)}</b></div><div><small>Urgence</small><b>${esc(cap(d.urgency))}</b></div>`;const order=['site','social','notification','reception'];outputsGrid.innerHTML=order.filter(k=>d.channels.includes(k)).map(k=>card(k,outs[k])).join('');results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'start'});show('Kit généré : brouillons prêts à relire.')}
function buildOutputs(d){const range=dateRange(d), action=d.noAction?'Aucune action n’est demandée aux habitants.':sentence(d.action);const website=`${d.subject.trim()}\n\n${sentence(d.change)}\n\nQui est concerné ?\n${sentence(d.audience)}\n\nQuand ?\n${range}\n\nOù ?\n${d.location.trim()}\n\nQuelles conséquences ?\n${sentence(d.impact)}\n\nQue faut-il faire ?\n${action}\n\nRenseignements\n${d.contact.trim()}`;const social=`${d.subject.trim()}\n\n${sentence(d.change)}\n\n📅 ${shortDate(d)}\n📍 ${d.location.trim()}\n\n${sentence(d.impact)}\n\n${action}\n\nRenseignements : ${d.contact.trim()}`;const contact=compactContact(d.contact), time=timeRange(d), lead=`${d.subject.trim()}${time?`, ${time}`:''} : `, tail=` Infos : ${contact}`, room=Math.max(24,160-lead.length-tail.length), notification=clamp(`${lead}${clamp(sentence(d.impact),room)}${tail}`.replace(/\s+/g,' ').trim(),160);const reception=`FICHE RÉPONSE — ACCUEIL MAIRIE\n\nSUJET\n${d.subject.trim()}\n\nMESSAGE À DONNER\n${sentence(d.change)}\n\n1. Quand : ${range}\n2. Où : ${d.location.trim()}\n3. Conséquence : ${sentence(d.impact)}\n4. Action attendue : ${action}\n\nSI UNE PRÉCISION EST DEMANDÉE\nOrienter vers : ${d.contact.trim()}\n\nRÉFÉRENCE INTERNE\nService : ${d.service}\nRéférent : ${d.requester.trim()||'À compléter'}\nSource : ${d.source.trim()}\nValidation : ${d.validator}`;return{site:{title:'Site internet',sub:'Article détaillé',badge:'WWW',text:website,note:'Version longue · informations pratiques incluses'},social:{title:'Réseaux sociaux',sub:'Facebook / Instagram',badge:'#',text:social,note:`${social.length} caractères`},notification:{title:'Notification',sub:'Application / alerte',badge:'!',text:notification,note:`${notification.length}/160 caractères`},reception:{title:'Accueil mairie',sub:'Fiche réponse interne',badge:'i',text:reception,note:'Version interne · traçabilité incluse'}}}
function card(key,o){return`<article class="output" data-output="${key}"><header><div class="output-title"><span class="badge">${esc(o.badge)}</span><span><b>${esc(o.title)}</b><small>${esc(o.sub)}</small></span></div><button class="copy" type="button" data-copy="${key}">Copier</button></header><pre>${esc(o.text)}</pre><footer><span>Brouillon à relire</span><span>${esc(o.note)}</span></footer></article>`}

async function copy(text,msg='Contenu copié.'){try{await navigator.clipboard.writeText(text)}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.append(ta);ta.select();document.execCommand('copy');ta.remove()}show(msg)}
function copyAll(){if(!generated)return;copy(generated.d.channels.map(k=>`=== ${generated.outs[k].title.toUpperCase()} ===\n${generated.outs[k].text}`).join('\n\n'),'Tout le kit a été copié.')}
function download(){if(!generated)return;const txt=`SPLN BRIEFCOM — KIT DE COMMUNICATION\nPrototype non officiel\n\n`+generated.d.channels.map(k=>`=== ${generated.outs[k].title.toUpperCase()} ===\n${generated.outs[k].text}`).join('\n\n')+`\n\n=== MÉTADONNÉES ===\nSource : ${generated.d.source}\nValidation : ${generated.d.validator}\n`;const blob=new Blob([txt],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`SPLN-BriefCom-${slug(generated.d.subject)}.txt`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);show('Kit téléchargé.')}
function show(msg){clearTimeout(toastTimer);toast.textContent=msg;toast.classList.add('show');toastTimer=setTimeout(()=>toast.classList.remove('show'),2400)}

function dateRange(d){if(!d.startDate)return'Date à confirmer';const start=formatDate(d.startDate,d.startTime);if(!d.endDate)return start;if(d.startDate===d.endDate){const day=formatDate(d.startDate,'');if(d.startTime&&d.endTime)return`${day}, de ${clock(d.startTime)} à ${clock(d.endTime)}`;if(d.startTime)return`${day}, à partir de ${clock(d.startTime)}`;return day}return`Du ${start} au ${formatDate(d.endDate,d.endTime)}`}
function shortDate(d){if(!d.startDate)return'Date à confirmer';const x=new Date(`${d.startDate}T12:00:00`),date=new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'long'}).format(x);return cap(date)+(d.startTime?` à ${clock(d.startTime)}`:'')}
function formatDate(v,t){const x=new Date(`${v}T12:00:00`),s=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(x);return cap(s)+(t?` à ${clock(t)}`:'')}
function timeRange(d){if(!d.startTime)return'';return d.endTime?`${compactClock(d.startTime)}–${compactClock(d.endTime)}`:`dès ${compactClock(d.startTime)}`}
function clock(v){return v.replace(':',' h ')} function compactClock(v){return v.replace(':00','h').replace(':','h')}
function compactContact(v){return(v.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)||v.match(/(?:\+33|0)[\d\s.()-]{8,}/)||[v])[0].trim()}
function sentence(v){let s=(v||'').trim();if(!s)return'';s=cap(s);return/[.!?]$/.test(s)?s:s+'.'} function cap(v){return v?v.charAt(0).toLocaleUpperCase('fr-FR')+v.slice(1):''}
function clamp(v,n){if(v.length<=n)return v;const s=v.slice(0,n-1),i=s.lastIndexOf(' ');return s.slice(0,Math.max(i,n-18)).trim()+'…'}
function slug(v){return(v||'kit').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'kit'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}

form.addEventListener('input',e=>{if(e.target.id==='no-action')syncAction();update()});form.addEventListener('change',e=>{if(e.target.id==='no-action')syncAction();update()});form.addEventListener('submit',e=>e.preventDefault());
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const action=a.dataset.action;if(action==='run-demo'){setData(complete);generate()}if(action==='raw-demo'){setData(raw);$('#workspace').scrollIntoView({behavior:'smooth'});show('Demande brute chargée : les manques sont signalés.')}if(action==='complete-demo'){setData(complete);$('#workspace').scrollIntoView({behavior:'smooth'});show('Scénario complété.')}if(action==='reset')reset();if(action==='back')$('#workspace').scrollIntoView({behavior:'smooth'})}const c=e.target.closest('[data-copy]');if(c&&generated){const k=c.dataset.copy;copy(generated.outs[k].text,`${generated.outs[k].title} copié.`)}});
generateBtn.addEventListener('click',generate);$('#copy-all').addEventListener('click',copyAll);$('#download-kit').addEventListener('click',download);$('#print-kit').addEventListener('click',()=>window.print());
if(!restore()){syncAction();update()}
})();
